#!/usr/bin/env python3
"""第二批补词：从557扩展到1000+"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.parent
DATA_FILE = SCRIPT_DIR / "data" / "frequency_1000.json"

# ========== 第二批：443个补充高频词（中级/进阶/雅思）==========
WORDS_BATCH2 = [
    # --- 更多动词 ---
    ("allow", "/əˈlaʊ/", "v. 允许；许可；给予", 1),
    ("apply", "/əˈplaɪ/", "v. 申请；应用；适用", 2),
    ("argue", "/ˈɑːrɡjuː/", "v. 争论；辩论；主张", 2),
    ("arrive", "/əˈraɪv/", "v. 到达；达成；发生", 1),
    ("attack", "/əˈtæk/", "v./n. 攻击；抨击；进攻", 2),
    ("attempt", "/əˈtempt/", "v./n. 尝试；企图", 2),
    ("attend", "/əˈtend/", "v. 出席；参加；照料", 2),
    ("avoid", "/əˈvɔɪd/", "v. 避免；回避；撤销", 2),
    ("beat", "/biːt/", "v./n. 打败；敲打；心跳", 1),
    ("blow", "/bləʊ/", "v. 吹；吹气；爆发", 1),
    ("break", "/breɪk/", "v./n. 打破；中断；休息", 1),
    ("bring", "/brɪŋ/", "v. 带来；拿来；引起", 1),
    ("build", "/bɪld/", "v. 建造；建立；发展", 1),
    ("burn", "/bɜːrn/", "v. 燃烧；烫伤；发光", 1),
    ("carry", "/ˈkæri/", "v. 携带；搬运；支撑", 1),
    ("catch", "/kætʃ/", "v. 抓住；赶上；理解", 1),
    ("celebrate", "/ˈselɪbreɪt/", "v. 庆祝；赞美；歌颂", 1),
    ("check", "/tʃek/", "v./n. 检查；核实；支票", 1),
    ("claim", "/kleɪm/", "v./n. 声称；要求；索赔", 3),
    ("clean", "/kliːn/", "adj./v. 干净的；打扫", 1),
    ("climb", "/klaɪm/", "v./n. 攀爬；攀登；上升", 1),
    ("close", "/kləʊz/", "v./adj. 关闭；接近的", 1),
    ("collect", "/kəˈlekt/", "v. 收集；收集；聚集", 2),
    ("compare", "/kəmˈpeər/", "v. 比较；对照；比作", 2),
    ("complete", "/kəmˈpliːt/", "adj./v. 完成的；完成", 1),
    ("continue", "/kənˈtɪnjuː/", "v. 继续；延续；保持", 1),
    ("control", "/kənˈtrəʊl/", "v./n. 控制；管理；操纵", 2),
    ("cook", "/kʊk/", "v./n. 烹饪；厨师", 1),
    ("cover", "/ˈkʌvər/", "v./n. 覆盖；包含；封面", 1),
    ("cross", "/krɒs/", "v./n. 穿越；交叉；十字", 1),
    ("cry", "/kraɪ/", "v./n. 哭泣；叫喊；哭声", 1),
    ("damage", "/ˈdæmɪdʒ/", "v./n. 损害；毁坏；损害", 2),
    ("dance", "/dɑːns/", "v./n. 跳舞；舞蹈", 1),
    ("deal", "/diːl/", "v./n. 处理；交易；发牌", 1),
    ("describe", "/dɪˈskraɪb/", "v. 描述；描绘；说明", 2),
    ("destroy", "/dɪˈstrɔɪ/", "v. 摧毁；破坏；消灭", 2),
    ("develop", "/dɪˈveləp/", "v. 发展；开发；冲洗（胶片）", 2),
    ("die", "/daɪ/", "v. 死亡；消失；渴望", 1),
    ("discover", "/dɪˈskʌvər/", "v. 发现；发觉；找到", 2),
    ("discuss", "/dɪˈskʌs/", "v. 讨论；论述；商讨", 2),
    ("drive", "/draɪv/", "v./n. 开车；驾驶；驱动", 1),
    ("drop", "/drɒp/", "v./n. 落下；掉落；一滴", 1),
    ("earn", "/ɜːrn/", "v. 赚取；获得；赢得", 1),
    ("explain", "/ɪkˈspleɪn/", "v. 解释；说明；辩解", 1),
    ("fail", "/feɪl/", "v. 失败；不及格；衰弱", 1),
    ("feed", "/fiːd/", "v. 喂养；供给；满足", 1),
    ("fill", "/fɪl/", "v. 装满；填充；担任", 1),
    ("fix", "/fɪks/", "v. 修理；固定；解决", 1),
    ("fly", "/flaɪ/", "v./n. 飞；飞行；苍蝇", 1),
    ("forget", "/fəˈɡet/", "v. 忘记；忽略；忘记", 1),
    ("forgive", "/fəˈɡɪv/", "v. 原谅；宽恕；免除", 1),
    ("gather", "/ˈɡæðər/", "v. 聚集；收集；收割", 2),
    ("grab", "/ɡræb/", "v. 抓取；抓住；抢走", 1),
    ("guess", "/ɡes/", "v./n. 猜测；推测；猜想", 1),
    ("hang", "/hæŋ/", "v. 悬挂；绞死；逗留", 1),
    ("hide", "/haɪd/", "v. 隐藏；躲避；掩盖", 1),
    ("imagine", "/ɪˈmædʒɪn/", "v. 想象；设想；猜测", 2),
    ("include", "/ɪnˈkluːd/", "v. 包括；包含；算在内", 1),
    ("increase", "/ɪnˈkriːs/", "v./n. 增加；增长；提高", 2),
    ("invite", "/ɪnˈvaɪt/", "v. 邀请；招致；请求", 1),
    ("jump", "/dʒʌmp/", "v./n. 跳跃；猛增；跳过", 1),
    ("kick", "/kɪk/", "v./n. 踢；踢腿；兴奋感", 1),
    ("knock", "/nɒk/", "v./n. 敲；撞击；批评", 1),
    ("laugh", "/lɑːf/", "v./n. 笑；嘲笑；笑声", 1),
    ("lay", "/leɪ/", "v. 放置；产卵；铺设", 1),
    ("lie", "/laɪ/", "v./n. 躺；撒谎；谎话", 1),
    ("lift", "/lɪft/", "v./n. 举起；电梯；搭车", 1),
    ("load", "/ləʊd/", "v./n. 装载；负担；加载", 1),
    ("lock", "/lɒk/", "v./n. 锁上；锁；水闸", 1),
    ("manage", "/ˈmænɪdʒ/", "v. 管理；设法完成；处理", 2),
    ("mark", "/mɑːrk/", "v./n. 标记；分数；记号", 1),
    ("match", "/mætʃ/", "v./n. 匹配；比赛；火柴", 1),
    ("mention", "/ˈmenʃn/", "v./n. 提及；提到；提及", 1),
    ("miss", "/mɪs/", "v. 想念；错过；未击中", 1),
    ("mix", "/mɪks/", "v. 混合；调配；混淆", 1),
    ("notice", "/ˈnəʊtɪs/", "v./n. 注意到；通知；通告", 1),
    ("order", "/ˈɔːrdər/", "v./n. 订单；命令；点餐", 1),
    ("pack", "/pæk/", "v./n. 打包；包装；背包", 1),
    ("paint", "/peɪnt/", "v./n. 画；油漆；涂料", 1),
    ("pick", "/pɪk/", "v. 挑选；采摘；捡起", 1),
    ("place", "/pleɪs/", "v./n. 放置；地方；位置", 1),
    ("press", "/pres/", "v./n. 按；压；出版社；新闻界", 1),
    ("produce", "/prəˈdjuːs/", "v./n. 生产；制作；农产品", 2),
    ("pull", "/pʊl/", "v. 拉；拖；吸引", 1),
    ("push", "/pʊʃ/", "v. 推；逼迫；促进", 1),
    ("rain", "/reɪn/", "v./n. 下雨；雨", 1),
    ("receive", "/rɪˈsiːv/", "v. 收到；接待；接受", 1),
    ("record", "/rɪˈkɔːrd/", "v./n. 记录；录音；唱片", 1),
    ("reduce", "/rɪˈdjuːs/", "v. 减少；降低；缩小", 2),
    ("refuse", "/rɪˈfjuːz/", "v./n. 拒绝；垃圾", 1),
    ("replace", "/rɪˈpleɪs/", "v. 取代；替换；放回原处", 2),
    ("rest", "/rest/", "v./n. 休息；剩余部分", 1),
    ("ride", "/raɪd/", "v./n. 骑乘；乘坐；骑行", 1),
    ("roll", "/rəʊl/", "v./n. 滚动；卷；面包卷", 1),
    ("save", "/seɪv/", "v. 救；储蓄；保存", 1),
    ("search", "/sɜːrtʃ/", "v./n. 搜索；搜寻；调查", 1),
    ("shake", "/ʃeɪk/", "v./n. 摇晃；握手；奶昔", 1),
    ("share", "/ʃeər/", "v./n. 分享；股份；份额", 1),
    ("shoot", "/ʃuːt/", "v. 射击；拍摄；发芽", 1),
    ("shout", "/ʃaʊt/", "v./n. 大喊；喊叫；呼喊", 1),
    ("sing", "/sɪŋ/", "v. 唱歌；鸣唱；吟诗", 1),
    ("sink", "/sɪŋk/", "v./n. 下沉；水池；洗涤槽", 1),
    ("skip", "/skɪp/", "v. 跳过；跳跃；跳绳", 1),
    ("smile", "/smaɪl/", "v./n. 微笑；笑容", 1),
    ("sound", "/saʊnd/", "v./n. 听起来；声音", 1),
    ("spread", "/spred/", "v./n. 传播；展开；涂抹", 2),
    ("steal", "/stiːl/", "v. 偷窃；盗窃；抄袭", 1),
    ("stick", "/stɪk/", "v./n. 粘贴；坚持；棍子", 1),
    ("swing", "/swɪŋ/", "v./n. 摇摆；秋千；挥舞", 1),
    ("switch", "/swɪtʃ/", "v./n. 切换；开关；转换", 1),
    ("taste", "/teɪst/", "v./n. 尝起来；味道；品味", 1),
    ("throw", "/θrəʊ/", "v. 扔；投掷；抛出", 1),
    ("touch", "/tʌtʃ/", "v./n. 触摸；接触；感觉", 1),
    ("trade", "/treɪd/", "v./n. 交易；贸易；交换", 1),
    ("travel", "/ˈtrævl/", "v./n. 旅行；行进；传播", 1),
    ("treat", "/triːt/", "v. 对待；治疗；款待", 1),
    ("trip", "/trɪp/", "n./v. 旅行；绊倒", 1),
    ("type", "/taɪp/", "v./n. 打字；类型；种类", 1),
    ("visit", "/ˈvɪzɪt/", "v./n. 参观；访问；拜访", 1),
    ("vote", "/vəʊt/", "v./n. 投票；选举；表决", 2),
    ("wait", "/weɪt/", "v. 等待；等候；推迟", 1),
    ("wave", "/weɪv/", "v./n. 挥手；波浪；波动", 1),
    ("wish", "/wɪʃ/", "v./n. 希望；愿望；想要", 1),
    ("worry", "/ˈwʌri/", "v./n. 担心；烦恼；忧虑", 1),
    ("wrap", "/ræp/", "v. 包裹；缠绕；结束", 1),

    # --- 更多名词 ---
    ("ability", "/əˈbɪləti/", "n. 能力；才能；本领", 2),
    ("accident", "/ˈæksɪdənt/", "n. 事故；意外；偶然", 2),
    ("action", "/ˈækʃn/", "n. 行动；作用；动作", 2),
    ("advice", "/ədˈvaɪs/", "n. 建议；忠告", 1),
    ("affair", "/əˈfeər/", "n. 事情；事件；事务", 2),
    ("age", "/eɪdʒ/", "n. 年龄；时代；老化", 1),
    ("agent", "/ˈeɪdʒənt/", "n. 代理人；经纪人；特工", 2),
    ("agreement", "/əˈɡriːmənt/", "n. 协议；同意；一致", 2),
    ("air", "/eər/", "n. 空气；气氛；曲调", 1),
    ("amount", "/əˈmaʊnt/", "n. 数量；金额；总数", 1),
    ("animal", "/ˈænɪml/", "n. 动物；兽类", 1),
    ("answer", "/ˈɑːnsər/", "n./v. 答案；回答", 1),
    ("area", "/ˈeəriə/", "n. 区域；地区；面积", 1),
    ("art", "/ɑːrt/", "n. 艺术；美术；技艺", 1),
    ("article", "/ˈɑːrtɪkl/", "n. 文章；物品；条款", 2),
    ("audience", "/ˈɔːdiəns/", "n. 观众；听众；读者", 2),
    ("award", "/əˈwɔːrd/", "n./v. 奖品；授予", 2),
    ("balance", "/ˈbæləns/", "n./v. 平衡；余额；使平衡", 2),
    ("base", "/beɪs/", "n./v. 基地；基础；以…为基础", 2),
    ("battle", "/ˈbætl/", "n./v. 战斗；斗争；搏斗", 2),
    ("beach", "/biːtʃ/", "n. 海滩；沙滩", 1),
    ("beauty", "/ˈbjuːti/", "n. 美；美女；美好事物", 1),
    ("behavior", "/bɪˈheɪvjər/", "n. 行为；表现；举止", 2),
    ("benefit", "/ˈbenɪfɪt/", "n./v. 利益；好处；有益于", 2),
    ("bill", "/bɪl/", "n. 账单；钞票；法案", 1),
    ("blood", "/blʌd/", "n. 血液；血统；血气", 1),
    ("boat", "/bəʊt/", "n. 小船；轮船；艇形物", 1),
    ("bone", "/bəʊn/", "n. 骨头；骨骼", 1),
    ("border", "/ˈbɔːrdər/", "n./v. 边界；边界；接壤", 2),
    ("bottom", "/ˈbɒtəm/", "n. 底部；臀部；最低的", 1),
    ("brand", "/brænd/", "n./v. 品牌；商标；烙印", 1),
    ("bridge", "/brɪdʒ/", "n. 桥；桥梁；鼻梁", 1),
    ("budget", "/ˈbʌdʒɪt/", "n./v. 预算；安排；低廉的", 2),
    ("building", "/ˈbɪldɪŋ/", "n. 建筑；建筑物；建造", 1),
    ("camera", "/ˈkæmrə/", "n. 相机；摄像机", 1),
    ("campus", "/ˈkæmpəs/", "n. 校园；大学校区", 2),
    ("cancer", "/ˈkænsər/", "n. 癌症；恶性肿瘤", 2),
    ("capital", "/ˈkæpɪtl/", "n. 首都；资本；大写字母", 2),
    ("captain", "/ˈkæptɪn/", "n. 船长；队长；上尉", 2),
    ("card", "/kɑːrd/", "n. 卡片；牌；卡片机", 1),
    ("cause", "/kɔːz/", "n./v. 原因；事业；导致", 2),
    ("center", "/ˈsentər/", "n. 中心；中央；核心", 1),
    ("century", "/ˈsentʃuri/", "n. 世纪；百年", 1),
    ("ceremony", "/ˈserɪməni/", "n. 典礼；仪式；礼节", 2),
    ("chance", "/tʃɑːns/", "n. 机会；可能性；运气", 1),
    ("change", "/tʃeɪndʒ/", "n./v. 变化；零钱；改变", 1),
    ("character", "/ˈkærəktər/", "n. 性格；角色；汉字", 2),
    ("charge", "/tʃɑːrdʒ/", "n./v. 收费；指控；负责", 2),
    ("choice", "/tʃɔɪs/", "n. 选择；抉择；精选品", 1),
    ("class", "/klɑːs/", "n. 班级；阶级；课", 1),
    ("climate", "/ˈklaɪmət/", "n. 气候；风气；氛围", 2),
    ("clothing", "/ˈkləʊðɪŋ/", "n. 衣服；服装", 1),
    ("cloud", "/klaʊd/", "n. 云；云状物；阴霾", 1),
    ("club", "/klʌb/", "n. 俱乐部；会所；棍棒", 1),
    ("coast", "/kəʊst/", "n. 海岸；沿海地区", 1),
    ("collection", "/kəˈlekʃn/", "n. 收藏品；收集；募捐", 2),
    ("comfort", "/ˈkʌmfərt/", "n./v. 舒适；安慰；使舒适", 2),
    ("company", "/ˈkʌmpəni/", "n. 公司；陪伴；同伴", 1),
    ("competition", "/ˌkɒmpəˈtɪʃn/", "n. 比赛；竞争；竞赛", 2),
    ("condition", "/kənˈdɪʃn/", "n. 条件；状况；环境", 2),
    ("connection", "/kəˈnekʃn/", "n. 连接；关系；联系", 2),
    ("corner", "/ˈkɔːrnər/", "n. 角落；街角；困境", 1),
    ("cost", "/kɒst/", "n./v. 成本；花费；价值", 1),
    ("country", "/ˈkʌntri/", "n. 国家；乡村；农村", 1),
    ("court", "/kɔːrt/", "n. 法院；球场；庭院", 2),
    ("culture", "/ˈkʌltʃər/", "n. 文化；文明；培养", 2),
    ("cup", "/kʌp/", "n. 杯子；奖杯；一杯", 1),
    ("danger", "/ˈdeɪndʒər/", "n. 危险；威胁；风险", 1),
    ("death", "/deθ/", "n. 死亡；死亡人数；消亡", 1),
    ("debt", "/det/", "n. 债务；欠款", 2),
    ("degree", "/dɪˈɡriː/", "n. 度数；学位；程度", 1),
    ("design", "/dɪˈzaɪn/", "n./v. 设计；图案；构思", 1),
    ("detail", "/ˈdiːteɪl/", "n. 细节；详情", 1),
    ("direction", "/dəˈrekʃn/", "n. 方向；指导；用法说明", 1),
    ("distance", "/ˈdistəns/", "n. 距离；远方；间隔", 2),
    ("dream", "/driːm/", "n./v. 梦；梦想；做梦", 1),
    ("earth", "/ɜːrθ/", "n. 地球；泥土；地面", 1),
    ("edge", "/edʒ/", "n. 边缘；刀刃；优势", 1),
    ("effect", "/ɪˈfekt/", "n. 效果；影响；结果", 2),
    ("effort", "/ˈefərt/", "n. 努力；成果；成就", 2),
    ("energy", "/ˈenərdʒi/", "n. 能量；精力；活力", 2),
    ("environment", "/ɪnˈvaɪrənmənt/", "n. 环境；周围；自然环境", 2),
    ("event", "/ɪˈvent/", "n. 事件；活动；大事", 1),
    ("experience", "/ɪkˈspɪəriəns/", "n./v. 经验；经历；体验", 1),
    ("expert", "/ˈekspɜːrt/", "n./adj. 专家；专业的", 2),
    ("factor", "/ˈfæktər/", "n. 因素；要素；系数", 2),
    ("fan", "/fæn/", "n. 迷；风扇；扇子", 1),
    ("farm", "/fɑːrm/", "n./v. 农场；耕种；养殖", 1),
    ("favor", "/ˈfeɪvər/", "n./v. 帮忙；偏爱；支持", 1),
    ("field", "/fiːld/", "n. 田地；领域；场地", 1),
    ("figure", "/ˈfɪɡjər/", "n. 数字；人物；身材", 2),
    ("flight", "/flaɪt/", "n. 航班；飞行；逃跑", 1),
    ("floor", "/flɔːr/", "n. 地板；楼层；底面", 1),
    ("focus", "/ˈfəʊkəs/", "n./v. 焦点；集中注意力", 2),
    ("force", "/fɔːrs/", "n./v. 力量；强迫；武力", 1),
    ("form", "/fɔːrm/", "n./v. 形式；表格；形成", 1),
    ("fortune", "/ˈfɔːrtʃuːn/", "n. 财富；运气；命运", 2),
    ("foundation", "/faʊnˈdeɪʃn/", "n. 基础；基金会；地基", 2),
    ("frame", "/freɪm/", "n./v. 框架；框架结构；陷害", 2),
    ("gas", "/ɡæs/", "n. 气；气体；汽油", 1),
    ("goal", "/ɡəʊl/", "n. 目标；进球；得分", 1),
    ("gold", "/ɡəʊld/", "n./adj. 金；金色的", 1),
    ("government", "/ˈɡʌvərnmənt/", "n. 政府；政体", 2),
    ("grass", "/ɡrɑːs/", "n. 草；草地；草坪", 1),
    ("ground", "/ɡraʊnd/", "n. 地面；土地；理由", 1),
    ("growth", "/ɡrəʊθ/", "n. 生长；增长；发展", 2),
    ("habit", "/ˈhæbɪt/", "n. 习惯；习性；嗜好", 1),
    ("hall", "/hɔːl/", "n. 大厅；走廊；礼堂", 1),
    ("heat", "/hiːt/", "n./v. 热；热度；加热", 1),
    ("height", "/haɪt/", "n. 高度；身高；高处", 1),
    ("history", "/ˈhɪstri/", "n. 历史；历史学", 1),
    ("hope", "/həʊp/", "n./v. 希望；期望；盼望", 1),
    ("hospital", "/ˈhɒspɪtl/", "n. 医院", 1),
    ("hotel", "/həʊˈtel/", "n. 酒店；旅馆", 1),
    ("ice", "/aɪs/", "n. 冰；冰块；冰激凌", 1),
    ("image", "/ˈɪmɪdʒ/", "n. 图像；形象；印象", 2),
    ("impact", "/ˈɪmpækt/", "n./v. 影响；冲击；碰撞", 2),
    ("industry", "/ˈɪndəstri/", "n. 工业；产业；行业", 2),
    ("interest", "/ˈɪntrəst/", "n./v. 兴趣；利息；使感兴趣", 1),
    ("item", "/ˈaɪtəm/", "n. 物品；项目；条款", 1),
    ("journey", "/ˈdʒɜːrni/", "n. 旅程；旅行；过程", 1),
    ("key", "/kiː/", "n. 钥匙；关键；答案", 1),
    ("knowledge", "/ˈnɒlɪdʒ/", "n. 知识；学问；了解", 1),
    ("land", "/lænd/", "n./v. 土地；陆地；着陆", 1),
    ("language", "/ˈlæŋɡwɪdʒ/", "n. 语言；语言能力", 1),
    ("layer", "/ˈleɪər/", "n. 层；层次；图层", 2),
    ("leader", "/ˈliːdər/", "n. 领导者；领袖", 2),
    ("length", "/leŋθ/", "n. 长度；长度单位", 1),
    ("level", "/ˈlevl/", "n./adj. 水平；级别；水平的", 1),
    ("limit", "/ˈlɪmɪt/", "n./v. 限制；限度；限制", 1),
    ("market", "/ˈmɑːrkɪt/", "n. 市场；行情；集市", 1),
    ("material", "/məˈtɪəriəl/", "n. 材料；原料；物质", 2),
    ("member", "/ˈmembər/", "n. 成员；会员；分子", 1),
    ("memory", "/ˈmeməri/", "n. 记忆；存储器；回忆", 1),
    ("message", "/ˈmesɪdʒ/", "n. 信息；消息；启示", 1),
    ("method", "/ˈmeθəd/", "n. 方法；办法；秩序", 2),
    ("mile", "/maɪl/", "n. 英里；很长的路", 1),
    ("mind", "/maɪnd/", "n./v. 思想；心智；介意", 1),
    ("model", "/ˈmɒdl/", "n./v. 模型；模特；做榜样", 1),
    ("mountain", "/ˈmaʊntən/", "n. 山；山脉", 1),
    ("movement", "/ˈmuːvmənt/", "n. 运动；动作；活动", 2),
    ("music", "/ˈmjuːzɪk/", "n. 音乐；乐曲；乐谱", 1),
    ("nature", "/ˈneɪtʃər/", "n. 自然；本质；本性", 1),
    ("news", "/njuːz/", "n. 新闻；消息", 1),
    ("noise", "/nɔɪz/", "n. 噪音；声音；杂音", 1),
    ("note", "/nəʊt/", "n./v. 笔记；音符；注意", 1),
    ("notebook", "/ˈnəʊtbʊk/", "n. 笔记本；笔记本电脑", 1),
    ("object", "/ˈɒbdʒɪkt/", "n./v. 物体；对象；反对", 2),
    ("occasion", "/əˈkeɪʒn/", "n. 场合；时机；原因", 2),
    ("ocean", "/ˈəʊʃn/", "n. 海洋；大量", 1),
    ("opportunity", "/ˌɒpərˈtuːnəti/", "n. 机会；时机", 2),
    ("option", "/ˈɒpʃn/", "n. 选择；选项", 1),
    ("order", "/ˈɔːrdər/", "n./v. 订单；顺序；命令", 1),
    ("pain", "/peɪn/", "n. 痛苦；疼痛；辛苦", 1),
    ("party", "/ˈpɑːrti/", "n. 派对；政党；聚会", 1),
    ("peace", "/piːs/", "n. 和平；安宁；平静", 1),
    ("period", "/ˈpɪəriəd/", "n. 时期；阶段；句号", 1),
    ("piece", "/piːs/", "n. 块；片；作品", 1),
    ("plan", "/plæn/", "n./v. 计划；打算；平面图", 1),
    ("policy", "/ˈpɒləsi/", "n. 政策；方针；保险单", 2),
    ("pollution", "/pəˈluːʃn/", "n. 污染；污染物", 2),
    ("position", "/pəˈzɪʃn/", "n. 位置；职位；立场", 1),
    ("price", "/praɪs/", "n. 价格；代价；代价", 1),
    ("pride", "/praɪd/", "n. 自豪；骄傲；得意", 1),
    ("process", "/ˈprəʊses/", "n./v. 过程；工序；加工", 2),
    ("product", "/ˈprɒdʌkt/", "n. 产品；制品；成果", 1),
    ("profit", "/ˈprɒfɪt/", "n./v. 利润；收益；获利", 2),
    ("progress", "/ˈprəʊɡres/", "n./v. 进步；进展；前进", 1),
    ("project", "/ˈprɒdʒekt/", "n./v. 项目；计划；投射", 1),
    ("purpose", "/ˈpɜːrpəs/", "n. 目的；用途；决心", 1),
    ("quality", "/ˈkwɒləti/", "n. 质量；品质；优质", 1),
    ("race", "/reɪs/", "n./v. 种族；赛跑；比赛", 1),
    ("range", "/reɪndʒ/", "n./v. 范围；范围变化；排列", 2),
    ("rate", "/reɪt/", "n./v. 比率；速度；评级", 2),
    ("record", "/ˈrekɔːrd/", "n./v. 记录；唱片；记录", 1),
    ("region", "/ˈriːdʒən/", "n. 地区；区域；部位", 2),
    ("research", "/rɪˈsɜːrtʃ/", "n./v. 研究；调查；探究", 2),
    ("resource", "/ˈriːsɔːrs/", "n. 资源；财力；智谋", 2),
    ("result", "/rɪˈzʌlt/", "n. 结果；成绩；后果", 1),
    ("role", "/rəʊl/", "n. 角色；作用；职能", 1),
    ("row", "/rəʊ/", "n. 排；列；行", 1),
    ("rule", "/ruːl/", "n./v. 规则；统治；规定", 1),
    ("salt", "/sɔːlt/", "n. 盐；盐类；刺激", 1),
    ("scene", "/siːn/", "n. 场景；场面；景色", 1),
    ("season", "/ˈsiːzn/", "n. 季节；季；赛季", 1),
    ("seat", "/siːt/", "n. 座位；席位；座位", 1),
    ("section", "/ˈsekʃn/", "n. 部分；部门；截面", 1),
    ("shape", "/ʃeɪp/", "n./v. 形状；形状塑造", 1),
    ("signal", "/ˈsɪɡnl/", "n./v. 信号；发信号", 2),
    ("site", "/saɪt/", "n. 地点；网站；现场", 1),
    ("size", "/saɪz/", "n. 大小；尺寸；规模", 1),
    ("skill", "/skɪl/", "n. 技能；技巧；熟练", 1),
    ("snow", "/snəʊ/", "n./v. 雪；下雪", 1),
    ("soil", "/sɔɪl/", "n. 土壤；土地；国土", 1),
    ("source", "/sɔːrs/", "n. 来源；源头；来源", 2),
    ("speed", "/spiːd/", "n./v. 速度；加速", 1),
    ("spirit", "/ˈspɪrɪt/", "n. 精神；情绪；烈酒", 2),
    ("spot", "/spɒt/", "n./v. 斑点；地点；发现", 1),
    ("stage", "/steɪdʒ/", "n. 舞台；阶段；步骤", 1),
    ("star", "/stɑːr/", "n./v. 星星；明星；主演", 1),
    ("step", "/step/", "n./v. 步骤；脚步；迈步", 1),
    ("stone", "/stəʊn/", "n. 石头；宝石；核", 1),
    ("storm", "/stɔːrm/", "n. 暴风雨；风波", 1),
    ("strength", "/streŋθ/", "n. 力量；强度；长处", 2),
    ("stress", "/stres/", "n./v. 压力；强调；重音", 2),
    ("style", "/staɪl/", "n. 风格；样式；时尚", 1),
    ("success", "/səkˈses/", "n. 成功；成就；胜利", 1),
    ("support", "/səˈpɔːrt/", "n./v. 支持；支撑；维持", 1),
    ("surface", "/ˈsɜːrfɪs/", "n. 表面；外观；表面", 2),
    ("system", "/ˈsɪstəm/", "n. 系统；制度；体系", 1),
    ("target", "/ˈtɑːrɡɪt/", "n./v. 目标；瞄准；目标对象", 2),
    ("task", "/tɑːsk/", "n. 任务；工作；作业", 1),
    ("temperature", "/ˈtemprətʃər/", "n. 温度；体温；发烧", 1),
    ("term", "/tɜːrm/", "n. 学期；术语；条件", 1),
    ("test", "/test/", "n./v. 测试；考试；检验", 1),
    ("text", "/tekst/", "n. 文本；课文；短信", 1),
    ("theory", "/ˈθiəri/", "n. 理论；学说；看法", 2),
    ("thought", "/θɔːt/", "n. 思想；想法；思考", 1),
    ("title", "/ˈtaɪtl/", "n. 标题；头衔；冠军", 1),
    ("top", "/tɒp/", "n./adj. 顶部；最高的", 1),
    ("tour", "/tʊər/", "n. 旅行；游览；巡回演出", 1),
    ("tradition", "/trəˈdɪʃn/", "n. 传统；惯例；习俗", 2),
    ("transport", "/ˈtrænspɔːrt/", "n./v. 交通；运输；运送", 2),
    ("tree", "/triː/", "n. 树；树木；家谱", 1),
    ("trip", "/trɪp/", "n./v. 旅行；出差；绊倒", 1),
    ("type", "/taɪp/", "n./v. 类型；类型打字", 1),
    ("value", "/ˈvæljuː/", "n. 价值；价值观；数值", 1),
    ("view", "/vjuː/", "n./v. 景色；观点；看待", 1),
    ("vision", "/ˈvɪʒn/", "n. 视力；愿景；想象", 2),
    ("voice", "/vɔɪs/", "n. 声音；嗓音；意见", 1),
    ("wall", "/wɔːl/", "n. 墙；墙壁；围墙", 1),
    ("war", "/wɔːr/", "n. 战争；冲突；斗争", 1),
    ("weight", "/weɪt/", "n. 重量；体重；重担", 1),
    ("window", "/ˈwɪndəʊ/", "n. 窗户；窗口；机会", 1),
    ("wing", "/wɪŋ/", "n. 翅膀；侧楼；翼", 1),
    ("wood", "/wʊd/", "n. 木头；森林；木材", 1),
    ("worker", "/ˈwɜːrkər/", "n. 工人；工作者", 1),
    ("world", "/wɜːrld/", "n. 世界；地球；领域", 1),

    # --- 更多形容词 ---
    ("able", "/ˈeɪbl/", "adj. 能够的；有能力的", 1),
    ("actual", "/ˈæktʃuəl/", "adj. 实际的；真实的", 2),
    ("amazing", "/əˈmeɪzɪŋ/", "adj. 令人惊奇的；极好的", 1),
    ("angry", "/ˈæŋɡri/", "adj. 生气的；愤怒的", 1),
    ("annoying", "/əˈnɔɪɪŋ/", "adj. 令人恼火的；讨厌的", 1),
    ("anxious", "/ˈæŋkʃəs/", "adj. 焦虑的；急切的", 2),
    ("appropriate", "/əˈprəʊpriət/", "adj. 合适的；适当的", 2),
    ("available", "/əˈveɪləbl/", "adj. 可用的；有空的", 2),
    ("aware", "/əˈweər/", "adj. 意识到的；知道的", 2),
    ("basic", "/ˈbeɪsɪk/", "adj. 基本的；基础的", 1),
    ("blank", "/blæŋk/", "adj./n. 空白的；空白", 1),
    ("bright", "/braɪt/", "adj. 明亮的；聪明的；鲜艳的", 1),
    ("busy", "/ˈbɪzi/", "adj. 忙碌的；繁忙的", 1),
    ("calm", "/kɑːm/", "adj. 冷静的；平静的", 1),
    ("careful", "/ˈkeərfl/", "adj. 仔细的；小心的", 1),
    ("cheap", "/tʃiːp/", "adj. 便宜的；廉价的", 1),
    ("clean", "/kliːn/", "adj. 干净的；整洁的", 1),
    ("clever", "/ˈklevər/", "adj. 聪明的；机灵的", 1),
    ("close", "/kləʊs/", "adj. 近的；紧密的", 1),
    ("common", "/ˈkɒmən/", "adj. 共同的；常见的", 1),
    ("complex", "/ˈkɒmpleks/", "adj. 复杂的；综合的", 2),
    ("confident", "/ˈkɒnfɪdənt/", "adj. 自信的；确信的", 1),
    ("confused", "/kənˈfjuːzd/", "adj. 困惑的；混乱的", 1),
    ("correct", "/kəˈrekt/", "adj. 正确的；恰当的", 1),
    ("curious", "/ˈkjʊəriəs/", "adj. 好奇的；奇特的", 2),
    ("current", "/ˈkʌrənt/", "adj. 当前的；流行的", 2),
    ("daily", "/ˈdeɪli/", "adj./adv. 每天的；日常", 1),
    ("deep", "/diːp/", "adj./adv. 深的；深深地", 1),
    ("delicious", "/dɪˈlɪʃəs/", "adj. 美味的；可口的", 1),
    ("difficult", "/ˈdɪfɪkəlt/", "adj. 困难的；艰难的", 1),
    ("direct", "/dəˈrekt/", "adj./adv. 直接的；直率地", 1),
    ("dirty", "/ˈdɜːrti/", "adj. 脏的；肮脏的", 1),
    ("dry", "/draɪ/", "adj. 干的；干燥的", 1),
    ("due", "/djuː/", "adj. 到期的；应有的", 2),
    ("easy", "/ˈiːzi/", "adj. 容易的；轻松的", 1),
    ("empty", "/ˈempti/", "adj. 空的；空洞的", 1),
    ("entire", "/ɪnˈtaɪər/", "adj. 全部的；整个的", 2),
    ("equal", "/ˈiːkwəl/", "adj./v. 平等的；等于", 1),
    ("essential", "/ɪˈsenʃl/", "adj. 必要的；本质的", 2),
    ("extra", "/ˈekstrə/", "adj./n. 额外的；额外费用", 1),
    ("extreme", "/ɪkˈstriːm/", "adj./n. 极端的；极端", 2),
    ("fair", "/feər/", "adj. 公平的；合理的；浅色的", 1),
    ("familiar", "/fəˈmɪliər/", "adj. 熟悉的；常见的", 1),
    ("famous", "/ˈfeɪməs/", "adj. 著名的；有名的", 1),
    ("fast", "/fɑːst/", "adj./adv. 快的；迅速的", 1),
    ("favorite", "/ˈfeɪvərɪt/", "n./adj. 最爱；最喜欢的", 1),
    ("final", "/ˈfaɪnl/", "adj. 最后的；最终的", 1),
    ("firm", "/fɜːrm/", "adj./n. 坚定的；公司", 2),
    ("flat", "/flæt/", "adj. 平的；公寓", 1),
    ("fresh", "/freʃ/", "adj. 新鲜的；精神饱满的", 1),
    ("friendly", "/ˈfrendli/", "adj. 友好的；亲切的", 1),
    ("full", "/fʊl/", "adj. 满的；完全的", 1),
    ("general", "/ˈdʒenrəl/", "adj. 总体的；普遍的；将军", 1),
    ("gentle", "/ˈdʒentl/", "adj. 温柔的；温和的", 1),
    ("glad", "/ɡlæd/", "adj. 高兴的；乐意的", 1),
    ("golden", "/ˈɡəʊldən/", "adj. 金色的；珍贵的", 1),
    ("grateful", "/ˈɡreɪtfl/", "adj. 感激的；感谢的", 1),
    ("heavy", "/ˈhevi/", "adj. 重的；沉重的", 1),
    ("huge", "/hjuːdʒ/", "adj. 巨大的；庞大的", 1),
    ("human", "/ˈhjuːmən/", "adj./n. 人类的；人", 1),
    ("hungry", "/ˈhʌŋɡri/", "adj. 饿的；渴望的", 1),
    ("impossible", "/ɪmˈpɒsəbl/", "adj. 不可能的；办不到的", 1),
    ("incredible", "/ɪnˈkredəbl/", "adj. 难以置信的；极好的", 1),
    ("interesting", "/ˈɪntrəstɪŋ/", "adj. 有趣的；引起兴趣的", 1),
    ("international", "/ˌɪntərˈnæʃnl/", "adj. 国际的", 2),
    ("legal", "/ˈliːɡl/", "adj. 合法的；法律的", 2),
    ("local", "/ˈləʊkl/", "adj. 当地的；局部的", 1),
    ("loose", "/luːs/", "adj. 松的；宽松的", 1),
    ("loud", "/laʊd/", "adj. 大声的；喧闹的", 1),
    ("low", "/ləʊ/", "adj./adv. 低的；低的", 1),
    ("main", "/meɪn/", "adj. 主要的；最重要的", 1),
    ("mental", "/ˈmentl/", "adj. 心理的；精神的", 2),
    ("modern", "/ˈmɒdn/", "adj. 现代的；时髦的", 1),
    ("native", "/ˈneɪtɪv/", "adj./n. 本土的；当地人", 2),
    ("natural", "/ˈnætʃrəl/", "adj. 自然的；天然的", 1),
    ("necessary", "/ˈnesəseri/", "adj. 必要的；必需的", 1),
    ("nervous", "/ˈnɜːrvəs/", "adj. 紧张的；焦虑的", 1),
    ("normal", "/ˈnɔːrml/", "adj. 正常的；普通的", 1),
    ("obvious", "/ˈɒbviəs/", "adj. 明显的；显然的", 1),
    ("odd", "/ɒd/", "adj. 奇怪的；奇数的", 1),
    ("official", "/əˈfɪʃl/", "adj./n. 官方的；官员", 2),
    ("okay", "/əʊˈkeɪ/", "adj./adv. 好的；可以", 1),
    ("ordinary", "/ˈɔːrdneri/", "adj. 普通的；平常的", 1),
    ("original", "/əˈrɪdʒənl/", "adj. 最初的；原创的", 1),
    ("overall", "/ˌəʊvərˈɔːl/", "adj. 全面的；总体的", 2),
    ("particular", "/pəˈtɪkjələr/", "adj. 特别的；特定的", 2),
    ("personal", "/ˈpɜːrsənl/", "adj. 个人的；私人的", 1),
    ("physical", "/ˈfɪzɪkl/", "adj. 身体的；物理的", 2),
    ("plain", "/pleɪn/", "adj. 简单的；朴素的；清楚的", 1),
    ("pleasant", "/ˈpleznt/", "adj. 令人愉快的；宜人的", 1),
    ("popular", "/ˈpɒpjələr/", "adj. 流行的；受欢迎的", 1),
    ("positive", "/ˈpɒzətɪv/", "adj. 积极的；正面的", 1),
    ("possible", "/ˈpɒsəbl/", "adj. 可能的；可行的", 1),
    ("private", "/ˈpraɪvɪt/", "adj. 私人的；私有的", 1),
    ("proper", "/ˈprɒpər/", "adj. 适当的；正确的", 1),
    ("public", "/ˈpʌblɪk/", "adj. 公众的；公共的", 1),
    ("quick", "/kwɪk/", "adj./adv. 快的；迅速的", 1),
    ("random", "/ˈrændəm/", "adj. 随机的；任意的", 1),
    ("rapid", "/ˈræpɪd/", "adj. 快速的；迅猛的", 2),
    ("rare", "/reər/", "adj. 罕见的；稀有的", 2),
    ("recent", "/ˈriːsnt/", "adj. 最近的；近来的", 1),
    ("regular", "/ˈreɡjələr/", "adj. 有规律的；定期的", 1),
    ("relevant", "/ˈreləvənt/", "adj. 相关的；切题的", 2),
    ("religious", "/rɪˈlɪdʒəs/", "adj. 宗教的；虔诚的", 2),
    ("responsible", "/rɪˈspɒnsəbl/", "adj. 负责的；可靠的", 2),
    ("rich", "/rɪtʃ/", "adj. 富有的；丰富的", 1),
    ("rough", "/rʌf/", "adj. 粗糙的；粗略的；艰难的", 1),
    ("round", "/raʊnd/", "adj./prep. 圆形的；围绕", 1),
    ("safe", "/seɪf/", "adj. 安全的；可靠的", 1),
    ("similar", "/ˈsɪmɪlər/", "adj. 相似的；类似的", 1),
    ("single", "/ˈsɪŋɡl/", "adj. 单一的；单个的", 1),
    ("smooth", "/smuːð/", "adj. 光滑的；顺利的", 1),
    ("social", "/ˈsəʊʃl/", "adj. 社会的；社交的", 2),
    ("soft", "/sɒft/", "adj. 软的；温柔的", 1),
    ("solid", "/ˈsɒlɪd/", "adj./n. 固体的；坚固的", 1),
    ("specific", "/spəˈsɪfɪk/", "adj. 特定的；具体的", 1),
    ("strange", "/streɪndʒ/", "adj. 奇怪的；陌生的", 1),
    ("straight", "/streɪt/", "adj./adv. 直的；直接地", 1),
    ("strong", "/strɒŋ/", "adj. 强壮的；强大的", 1),
    ("successful", "/səkˈsesfl/", "adj. 成功的；有成效的", 1),
    ("suitable", "/ˈsuːtəbl/", "adj. 合适的；适当的", 2),
    ("super", "/suːpər/", "adj./adv. 极好的；超级", 1),
    ("sure", "/ʃʊər/", "adj. 确信的；肯定的", 1),
    ("sweet", "/swiːt/", "adj. 甜的；可爱的", 1),
    ("thick", "/θɪk/", "adj. 厚的；浓密的", 1),
    ("thin", "/θɪn/", "adj. 薄的；瘦的", 1),
    ("tight", "/taɪt/", "adj. 紧的；严格的", 1),
    ("tiny", "/ˈtaɪni/", "adj. 微小的；极小的", 1),
    ("total", "/ˈtəʊtl/", "adj./n. 总计的；全部", 1),
    ("tough", "/tʌf/", "adj. 困难的；坚韧的", 1),
    ("traditional", "/trəˈdɪʃənl/", "adj. 传统的；惯例的", 2),
    ("true", "/truː/", "adj. 真实的；正确的", 1),
    ("typical", "/ˈtɪpɪkl/", "adj. 典型的；特有的", 2),
    ("ugly", "/ˈʌɡli/", "adj. 丑陋的；难看的", 1),
    ("unusual", "/ʌnˈjuːʒuəl/", "adj. 不寻常的；独特的", 1),
    ("usual", "/ˈjuːʒuəl/", "adj. 通常的；寻常的", 1),
    ("various", "/ˈveriəs/", "adj. 各种各样的；不同的", 1),
    ("warm", "/wɔːrm/", "adj. 温暖的；热情的", 1),
    ("weak", "/wiːk/", "adj. 弱的；虚弱的", 1),
    ("wide", "/waɪd/", "adj./adv. 宽的；广泛地", 1),
    ("wild", "/waɪld/", "adj. 野生的；狂野的", 1),
    ("wise", "/waɪz/", "adj. 明智的；聪明的", 1),
    ("worth", "/wɜːrθ/", "adj. 值得的；值…钱的", 1),
    ("wrong", "/rɒŋ/", "adj. 错误的；不正常的", 1),
    ("young", "/jʌŋ/", "adj. 年轻的；年幼的", 1),

    # --- 口语/习语短语 ---
    ("by the way", "/baɪ ðə weɪ/", "phrase 顺便说一句；对了", 1),
    ("at least", "/æt liːst/", "phrase 至少", 1),
    ("of course", "/əv kɔːrs/", "phrase 当然；当然可以", 1),
    ("in fact", "/ɪn fækt/", "phrase 事实上；其实", 1),
    ("no way", "/nəʊ weɪ/", "phrase 不可能；没门", 1),
    ("for sure", "/fɔːr ʃʊr/", "phrase 确定；肯定", 1),
    ("right away", "/raɪt əˈweɪ/", "phrase 立刻；马上", 1),
    ("so far", "/səʊ fɑːr/", "phrase 到目前为止；迄今为止", 1),
    ("all right", "/ɔːl raɪt/", "phrase 好吧；行", 1),
    ("come on", "/kʌm ɒn/", "phrase 加油；来吧；拜托", 1),
    ("look out", "/lʊk aʊt/", "phrase 当心；小心", 1),
    ("take care", "/teɪk keər/", "phrase 保重；小心", 1),
    ("go on", "/ɡəʊ ɒn/", "phrase 继续；进行", 1),
    ("hang on", "/hæŋ ɒn/", "phrase 稍等；别挂断", 1),
    ("give up", "/ɡɪv ʌp/", "phrase 放弃；投降", 1),
    ("pick up", "/pɪk ʌp/", "phrase 捡起；接人；学会", 1),
    ("set up", "/set ʌp/", "phrase 建立；安装；设置", 1),
    ("turn on", "/tɜːrn ɒn/", "phrase 打开；开启", 1),
    ("turn off", "/tɜːrn ɒf/", "phrase 关闭；关掉", 1),
    ("find out", "/faɪnd aʊt/", "phrase 发现；查明", 1),
    ("work out", "/wɜːrk aʊt/", "phrase 解决；锻炼成功；计算", 1),
]


def build_friends_scene(word, meaning):
    """生成老友记风格对话"""
    core_meaning = meaning.split("；")[0].replace("v. ","").replace("n. ","").replace("adj. ","").replace("adv. ","").replace("pron. ","").replace("prep. ","").replace("conj. ","").replace("int. ","").replace("phrase ","").strip()
    
    scene = (
        f'Rachel: Have you heard about "{word}"?\n'
        f'Joey: Yeah! It means {core_meaning}.\n'
        f'Chandler: Joey knows everything about "{word}".\n'
        f'Monica: Can we just order some food and stop talking about grammar?'
    )
    cn = (
        f'瑞秋：你听说过"{word}"吗？\n'
        f'乔伊：当然！意思是{core_meaning}。\n'
        f'钱德勒：乔伊什么都知道。\n'
        f'莫妮卡：我们能先点菜吗？别再讨论语法了。'
    )
    return scene, cn


def make_sentence(word, meaning):
    """生成简单例句"""
    core = meaning.split("；")[0]
    core_clean = core.replace("v. ","").replace("n. ","").replace("adj. ","").replace("adv. ","").replace("pron. ","").replace("prep. ","").replace("conj. ","").replace("int. ","").replace("phrase ","").strip()
    
    return (f"I want to learn how to use '{word}' correctly.", f"我想学习如何正确使用'{word}'。")


def main():
    with open(DATA_FILE, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    existing_words = {w['word'].lower() for w in existing}
    print(f"现有词库: {len(existing)} 个词")
    
    new_entries = []
    skipped = 0
    
    for item in WORDS_BATCH2:
        word, phonetic, meaning, level = item
        if word.lower() in existing_words:
            skipped += 1
            continue
        
        sentence, sentence_cn = make_sentence(word, meaning)
        scene, scene_cn = build_friends_scene(word, meaning)
        
        entry = {
            "word": word,
            "phonetic": phonetic,
            "meaning": meaning,
            "level": level,
            "sentence": sentence,
            "sentence_cn": sentence_cn,
            "friends_scene": scene,
            "friends_cn": scene_cn
        }
        new_entries.append(entry)
        existing_words.add(word.lower())
    
    print(f"跳过重复: {skipped}, 新增: {len(new_entries)}")
    
    combined = existing + new_entries
    seen = set()
    deduped = []
    for w in combined:
        k = w['word'].lower()
        if k not in seen:
            seen.add(k)
            deduped.append(w)
    
    deduped.sort(key=lambda x: (x.get('level',1), x['word'].lower()))
    
    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        json.dump(deduped, f, ensure_ascii=False, indent=2)
    
    total = len(deduped)
    print(f"✅ 词库更新完毕: {total} 个词")
    
    if total >= 1000:
        print("🎉 达成1000词目标！")
    else:
        print(f"📈 还差 {1000-total} 词达到1000")


if __name__ == "__main__":
    main()
