#!/usr/bin/env python3
"""
词库扩展脚本：从110个扩展到1000个高频词
使用英语词频表 + 老友记场景生成器
"""

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.parent
DATA_FILE   = SCRIPT_DIR / "data" / "frequency_1000.json"
EXPAND_FILE = SCRIPT_DIR / "data" / "words_batch.json"

# ========== 900个英语高频词（去除已有的110个，按词频排序）==========
# 来源：COCA语料库 + 英语口语高频词表 + 老友记常用词
# level说明：1=最基础 2=日常口语 3=中级 4=进阶 5=雅思

WORDS_TO_ADD = [
    # --- 功能词/代词/助动词 ---
    ("he", "/hiː/", "pron. 他", 1),
    ("she", "/ʃiː/", "pron. 她", 1),
    ("we", "/wiː/", "pron. 我们", 1),
    ("they", "/ðeɪ/", "pron. 他们", 1),
    ("it", "/ɪt/", "pron. 它", 1),
    ("this", "/ðɪs/", "pron./adj. 这；这个", 1),
    ("that", "/ðæt/", "pron./adj. 那；那个", 1),
    ("these", "/ðiːz/", "pron./adj. 这些", 1),
    ("those", "/ðəʊz/", "pron./adj. 那些", 1),
    ("my", "/maɪ/", "pron. 我的", 1),
    ("his", "/hɪz/", "pron. 他的", 1),
    ("her", "/hɜːr/", "pron. 她的；她", 1),
    ("its", "/ɪts/", "pron. 它的", 1),
    ("our", "/aʊər/", "pron. 我们的", 1),
    ("their", "/ðeər/", "pron. 他们的", 1),
    ("me", "/miː/", "pron. 我（宾格）", 1),
    ("him", "/hɪm/", "pron. 他（宾格）", 1),
    ("us", "/ʌs/", "pron. 我们（宾格）", 1),
    ("them", "/ðem/", "pron. 他们（宾格）", 1),
    ("who", "/huː/", "pron. 谁；who", 1),
    ("what", "/wɒt/", "pron./adj. 什么；多么", 1),
    ("which", "/wɪtʃ/", "pron./adj. 哪个；哪些", 1),
    ("where", "/weər/", "adv. 在哪里；哪里", 1),
    ("when", "/wen/", "adv./conj. 什么时候；当……时", 1),
    ("why", "/waɪ/", "adv. 为什么", 1),
    ("how", "/haʊ/", "adv. 怎么；多么", 1),
    ("some", "/sʌm/", "adj./pron. 一些；某些", 1),
    ("any", "/ˈeni/", "adj./pron. 任何；一些", 1),
    ("no", "/nəʊ/", "adv./adj. 不；没有", 1),
    ("each", "/iːtʃ/", "adj./pron. 每个；各自", 1),
    ("every", "/ˈevri/", "adj. 每；每一", 1),
    ("both", "/bəʊθ/", "adj./pron. 两者都；双方", 1),
    ("either", "/ˈaɪðər/", "adj./pron. 任一；两者之一", 2),
    ("neither", "/ˈnaɪðər/", "adj./pron. 两者都不", 2),
    ("another", "/əˈnʌðər/", "adj./pron. 另一个；再一个", 1),
    ("other", "/ˈʌðər/", "adj./pron. 其他的；别的", 1),
    ("such", "/sʌtʃ/", "adj./pron. 这样的；如此的", 2),
    ("same", "/seɪm/", "adj. 相同的；同样的", 1),
    ("own", "/əʊn/", "adj./v. 自己的；拥有", 2),
    ("few", "/fjuː/", "adj./pron. 几个；少数", 2),
    ("more", "/mɔːr/", "adj./adv. 更多；再", 1),
    ("most", "/məʊst/", "adj./adv. 最多；非常", 1),
    ("much", "/mʌtʃ/", "adj./adv. 许多；非常", 1),
    ("many", "/ˈmeni/", "adj./pron. 许多；很多", 1),
    ("less", "/les/", "adj./adv. 更少；较少", 1),
    ("little", "/ˈlɪtl/", "adj./adv. 小的；几乎没有", 1),
    ("enough", "/ɪˈnʌf/", "adj./adv. 足够的；充分地", 1),
    # --- 常用动词 ---
    ("be", "/biː/", "v. 是；存在；成为", 1),
    ("have", "/hæv/", "v. 有；吃；经历", 1),
    ("do", "/duː/", "v. 做；干；执行", 1),
    ("say", "/seɪ/", "v. 说；讲；表达", 1),
    ("get", "/ɡet/", "v. 得到；变得；到达", 1),
    ("make", "/meɪk/", "v. 制作；使得；赚", 1),
    ("go", "/ɡəʊ/", "v. 去；走；进行", 1),
    ("know", "/nəʊ/", "v. 知道；了解；认识", 1),
    ("take", "/teɪk/", "v. 拿；取；花费", 1),
    ("see", "/siː/", "v. 看见；明白；遇见", 1),
    ("come", "/kʌm/", "v. 来；到达；出现", 1),
    ("think", "/θɪŋk/", "v. 认为；想；思考", 1),
    ("look", "/lʊk/", "v. 看；显得；寻找", 1),
    ("want", "/wɒnt/", "v. 想要；需要", 1),
    ("give", "/ɡɪv/", "v. 给；赠予；提供", 1),
    ("use", "/juːz/", "v. 使用；利用", 1),
    ("find", "/faɪnd/", "v. 找到；发现；认为", 1),
    ("tell", "/tel/", "v. 告诉；讲；辨别", 1),
    ("ask", "/ɑːsk/", "v. 问；请求；邀请", 1),
    ("seem", "/siːm/", "v. 似乎；好像", 1),
    ("feel", "/fiːl/", "v. 感觉；觉得；摸", 1),
    ("try", "/traɪ/", "v. 尝试；试图；努力", 1),
    ("leave", "/liːv/", "v. 离开；留下；遗忘", 1),
    ("call", "/kɔːl/", "v. 打电话；叫做；称呼", 1),
    ("keep", "/kiːp/", "v. 保持；保留；继续", 1),
    ("let", "/let/", "v. 让；允许；出租", 1),
    ("begin", "/bɪˈɡɪn/", "v. 开始；着手", 1),
    ("show", "/ʃəʊ/", "v. 展示；表明；显示", 1),
    ("hear", "/hɪər/", "v. 听到；听说；得知", 1),
    ("play", "/pleɪ/", "v. 玩；演奏；扮演", 1),
    ("run", "/rʌn/", "v. 跑；运行；管理", 1),
    ("move", "/muːv/", "v. 移动；搬家；感动", 1),
    ("live", "/lɪv/", "v. 居住；生活；存活", 1),
    ("believe", "/bɪˈliːv/", "v. 相信；认为；信仰", 1),
    ("hold", "/həʊld/", "v. 拿；持有；举行", 2),
    ("bring", "/brɪŋ/", "v. 带来；拿来；引起", 1),
    ("happen", "/ˈhæpən/", "v. 发生；碰巧", 1),
    ("write", "/raɪt/", "v. 写；写作；填写", 1),
    ("provide", "/prəˈvaɪd/", "v. 提供；供给；规定", 2),
    ("sit", "/sɪt/", "v. 坐；坐落；开庭", 1),
    ("stand", "/stænd/", "v. 站；忍受；处于", 1),
    ("lose", "/luːz/", "v. 失去；迷失；输掉", 1),
    ("pay", "/peɪ/", "v. 付钱；偿还；注意", 1),
    ("meet", "/miːt/", "v. 遇见；满足；开会", 1),
    ("set", "/set/", "v. 设置；放置；建立", 1),
    ("learn", "/lɜːrn/", "v. 学习；了解；得知", 1),
    ("change", "/tʃeɪndʒ/", "v./n. 改变；变化；零钱", 1),
    ("lead", "/liːd/", "v. 领导；导致；领先", 2),
    ("understand", "/ˌʌndəˈstænd/", "v. 理解；明白；得知", 1),
    ("watch", "/wɒtʃ/", "v. 观看；注意；监视", 1),
    ("follow", "/ˈfɒləʊ/", "v. 跟随；遵循；关注", 1),
    ("stop", "/stɒp/", "v. 停止；阻止；停留", 1),
    ("create", "/kriˈeɪt/", "v. 创造；产生；引起", 2),
    ("speak", "/spiːk/", "v. 说话；演讲；讲", 1),
    ("read", "/riːd/", "v. 读；阅读；理解", 1),
    ("spend", "/spend/", "v. 花费；度过；消耗", 1),
    ("grow", "/ɡrəʊ/", "v. 生长；成长；增长", 1),
    ("open", "/ˈəʊpən/", "v./adj. 打开；开放；公开", 1),
    ("walk", "/wɔːk/", "v. 走路；散步；遛", 1),
    ("win", "/wɪn/", "v. 赢得；获胜；取得", 1),
    ("offer", "/ˈɒfər/", "v./n. 提供；提议；出价", 2),
    ("remember", "/rɪˈmembər/", "v. 记住；记得；纪念", 1),
    ("love", "/lʌv/", "v./n. 爱；喜欢；热爱", 1),
    ("consider", "/kənˈsɪdər/", "v. 考虑；认为；体谅", 2),
    ("appear", "/əˈpɪər/", "v. 出现；似乎；登台", 2),
    ("buy", "/baɪ/", "v. 购买；相信；贿赂", 1),
    ("wait", "/weɪt/", "v. 等待；等候；推迟", 1),
    ("send", "/send/", "v. 发送；派遣；传达", 1),
    ("expect", "/ɪkˈspekt/", "v. 期望；预计；要求", 2),
    ("build", "/bɪld/", "v. 建造；建立；增强", 1),
    ("stay", "/steɪ/", "v. 待；停留；保持", 1),
    ("fall", "/fɔːl/", "v. 落下；跌倒；降低", 1),
    ("cut", "/kʌt/", "v. 切；减少；穿过", 1),
    ("reach", "/riːtʃ/", "v. 到达；伸出；联系", 1),
    ("kill", "/kɪl/", "v. 杀死；消灭；使痛苦", 2),
    ("remain", "/rɪˈmeɪn/", "v. 剩余；保持；遗留", 2),
    ("suggest", "/səˈdʒest/", "v. 建议；暗示；表明", 2),
    ("raise", "/reɪz/", "v. 提高；养育；筹集", 2),
    ("pass", "/pɑːs/", "v. 通过；经过；传递", 1),
    ("sell", "/sel/", "v. 卖；销售；推销", 1),
    ("require", "/rɪˈkwaɪər/", "v. 需要；要求；规定", 2),
    ("report", "/rɪˈpɔːrt/", "v./n. 报告；汇报；报道", 2),
    ("decide", "/dɪˈsaɪd/", "v. 决定；判决；解决", 1),
    ("pull", "/pʊl/", "v. 拉；拖；吸引", 1),
    ("push", "/pʊʃ/", "v. 推；逼迫；促进", 1),
    ("turn", "/tɜːrn/", "v. 转；变成；轮到", 1),
    ("help", "/help/", "v./n. 帮助；援助；有益", 1),
    ("talk", "/tɔːk/", "v./n. 说话；谈话；演讲", 1),
    ("start", "/stɑːrt/", "v./n. 开始；出发；惊吓", 1),
    ("show", "/ʃəʊ/", "v./n. 展示；表明；节目", 1),
    ("need", "/niːd/", "v./n. 需要；必要；贫困", 1),
    ("work", "/wɜːrk/", "v./n. 工作；运转；作品", 1),
    ("put", "/pʊt/", "v. 放；置；表达", 1),
    ("mean", "/miːn/", "v./adj. 意思是；卑鄙的", 1),
    ("point", "/pɔɪnt/", "v./n. 指；要点；分数", 1),
    ("like", "/laɪk/", "v./prep. 喜欢；像；例如", 1),
    ("eat", "/iːt/", "v. 吃；侵蚀；烦扰", 1),
    ("sleep", "/sliːp/", "v./n. 睡觉；睡眠", 1),
    ("drink", "/drɪŋk/", "v./n. 喝；饮料；饮酒", 1),
    ("wear", "/weər/", "v. 穿；戴；磨损", 1),
    ("break", "/breɪk/", "v./n. 打破；休息；间隔", 1),
    ("hit", "/hɪt/", "v./n. 打；击中；成功", 1),
    ("throw", "/θrəʊ/", "v. 扔；投；抛", 1),
    ("catch", "/kætʃ/", "v. 抓住；赶上；理解", 1),
    ("choose", "/tʃuːz/", "v. 选择；挑选；决定", 1),
    ("accept", "/əkˈsept/", "v. 接受；承认；同意", 2),
    ("check", "/tʃek/", "v./n. 检查；核实；支票", 1),
    ("help", "/help/", "v./n. 帮助；援助；服务员", 1),
    ("serve", "/sɜːrv/", "v. 服务；供应；服役", 2),
    ("return", "/rɪˈtɜːrn/", "v./n. 返回；归还；回报", 1),
    ("care", "/keər/", "v./n. 关心；照顾；在意", 1),
    ("miss", "/mɪs/", "v. 想念；错过；未击中", 1),
    ("join", "/dʒɔɪn/", "v. 加入；连接；参加", 1),
    ("fight", "/faɪt/", "v./n. 打架；斗争；努力", 2),
    ("agree", "/əˈɡriː/", "v. 同意；赞成；一致", 1),
    ("wish", "/wɪʃ/", "v./n. 希望；祝愿；愿望", 1),
    ("plan", "/plæn/", "v./n. 计划；打算；方案", 1),
    ("wake", "/weɪk/", "v. 醒来；唤醒；守灵", 1),
    ("happen", "/ˈhæpən/", "v. 发生；碰巧；偶然", 1),
    ("wonder", "/ˈwʌndər/", "v./n. 想知道；惊奇；奇迹", 1),
    ("worry", "/ˈwʌri/", "v./n. 担心；烦恼；使忧虑", 1),
    ("hurt", "/hɜːrt/", "v./adj. 伤害；使疼痛；受伤", 1),
    ("promise", "/ˈprɒmɪs/", "v./n. 承诺；保证；前途", 1),
    ("protect", "/prəˈtekt/", "v. 保护；防护；守护", 2),
    ("die", "/daɪ/", "v. 死；消失；渴望", 1),
    ("save", "/seɪv/", "v. 救；储蓄；省去", 1),
    ("share", "/ʃeər/", "v./n. 分享；分担；股份", 1),
    ("try", "/traɪ/", "v./n. 尝试；努力；审判", 1),
    ("avoid", "/əˈvɔɪd/", "v. 避免；回避；撤销", 2),
    ("trust", "/trʌst/", "v./n. 信任；信赖；托管", 2),
    ("enjoy", "/ɪnˈdʒɔɪ/", "v. 享受；喜爱；欣赏", 1),
    ("improve", "/ɪmˈpruːv/", "v. 改善；提高；利用", 2),
    ("contain", "/kənˈteɪn/", "v. 包含；容纳；控制", 2),
    ("choose", "/tʃuːz/", "v. 选择；挑选；情愿", 1),
    # --- 常用名词 ---
    ("time", "/taɪm/", "n. 时间；次数；时代", 1),
    ("people", "/ˈpiːpl/", "n. 人；人们；民族", 1),
    ("man", "/mæn/", "n. 男人；人类；成年人", 1),
    ("woman", "/ˈwʊmən/", "n. 女人；女性", 1),
    ("child", "/tʃaɪld/", "n. 孩子；儿童", 1),
    ("day", "/deɪ/", "n. 天；日子；白天", 1),
    ("world", "/wɜːrld/", "n. 世界；地球；领域", 1),
    ("life", "/laɪf/", "n. 生命；生活；一生", 1),
    ("hand", "/hænd/", "n. 手；指针；帮助", 1),
    ("eye", "/aɪ/", "n. 眼睛；视力；眼光", 1),
    ("face", "/feɪs/", "n. 脸；表情；面对", 1),
    ("home", "/həʊm/", "n. 家；故乡；老家", 1),
    ("place", "/pleɪs/", "n. 地方；位置；名次", 1),
    ("case", "/keɪs/", "n. 情况；案例；病例", 2),
    ("week", "/wiːk/", "n. 周；星期", 1),
    ("thing", "/θɪŋ/", "n. 事；物；情况", 1),
    ("man", "/mæn/", "n. 男人；人类", 1),
    ("city", "/ˈsɪti/", "n. 城市；都市", 1),
    ("country", "/ˈkʌntri/", "n. 国家；农村；乡下", 1),
    ("school", "/skuːl/", "n. 学校；上学；学派", 1),
    ("family", "/ˈfæməli/", "n. 家庭；家人；种族", 1),
    ("group", "/ɡruːp/", "n. 群；组；集团", 1),
    ("problem", "/ˈprɒbləm/", "n. 问题；难题；麻烦", 1),
    ("fact", "/fækt/", "n. 事实；实际；真相", 1),
    ("idea", "/aɪˈdɪə/", "n. 想法；主意；概念", 1),
    ("room", "/ruːm/", "n. 房间；空间；余地", 1),
    ("way", "/weɪ/", "n. 方式；道路；方向", 1),
    ("money", "/ˈmʌni/", "n. 钱；金钱；财富", 1),
    ("story", "/ˈstɔːri/", "n. 故事；楼层；报道", 1),
    ("job", "/dʒɒb/", "n. 工作；职业；任务", 1),
    ("back", "/bæk/", "n./adv. 背部；后面；回", 1),
    ("body", "/ˈbɒdi/", "n. 身体；团体；主体", 1),
    ("door", "/dɔːr/", "n. 门；入口；家", 1),
    ("eye", "/aɪ/", "n. 眼睛；视力", 1),
    ("friend", "/frend/", "n. 朋友；友人；支持者", 1),
    ("father", "/ˈfɑːðər/", "n. 父亲；父；神父", 1),
    ("mother", "/ˈmʌðər/", "n. 母亲；妈妈；根源", 1),
    ("water", "/ˈwɔːtər/", "n. 水；水域；水位", 1),
    ("food", "/fuːd/", "n. 食物；食品；养料", 1),
    ("bed", "/bed/", "n. 床；花圃；河床", 1),
    ("name", "/neɪm/", "n. 名字；名声；姓名", 1),
    ("mind", "/maɪnd/", "n. 思想；心智；注意", 1),
    ("heart", "/hɑːrt/", "n. 心；心脏；中心", 1),
    ("head", "/hed/", "n. 头；首领；顶部", 1),
    ("hair", "/heər/", "n. 头发；毛发", 1),
    ("car", "/kɑːr/", "n. 汽车；车厢", 1),
    ("book", "/bʊk/", "n. 书；账册；预定", 1),
    ("number", "/ˈnʌmbər/", "n. 数字；号码；数量", 1),
    ("night", "/naɪt/", "n. 夜晚；夜间；黑暗", 1),
    ("line", "/laɪn/", "n. 线；行；台词", 1),
    ("word", "/wɜːrd/", "n. 单词；话；消息", 1),
    ("game", "/ɡeɪm/", "n. 游戏；比赛；猎物", 1),
    ("side", "/saɪd/", "n. 边；侧；方面", 1),
    ("kind", "/kaɪnd/", "n./adj. 种类；友好的", 1),
    ("end", "/end/", "n./v. 末端；结束；目的", 1),
    ("hand", "/hænd/", "n. 手；帮助；指针", 1),
    ("air", "/eər/", "n. 空气；气氛；曲调", 1),
    ("table", "/ˈteɪbl/", "n. 桌子；表格；目录", 1),
    ("office", "/ˈɒfɪs/", "n. 办公室；职务；机关", 1),
    ("eye", "/aɪ/", "n. 眼睛；眼光；小孔", 1),
    ("part", "/pɑːrt/", "n./v. 部分；零件；分开", 1),
    ("street", "/striːt/", "n. 街道；街；大街", 1),
    ("answer", "/ˈɑːnsər/", "n./v. 答案；回答；响应", 1),
    ("house", "/haʊs/", "n. 房子；家庭；议院", 1),
    ("point", "/pɔɪnt/", "n./v. 要点；分；指向", 1),
    ("reason", "/ˈriːzn/", "n./v. 原因；理由；推理", 1),
    ("result", "/rɪˈzʌlt/", "n./v. 结果；成果；导致", 2),
    ("question", "/ˈkwestʃən/", "n./v. 问题；疑问；质疑", 1),
    ("state", "/steɪt/", "n./v. 状态；州；陈述", 2),
    ("minute", "/ˈmɪnɪt/", "n. 分钟；时刻；备忘录", 1),
    ("moment", "/ˈməʊmənt/", "n. 片刻；时刻；重要性", 1),
    ("sense", "/sens/", "n./v. 感觉；意义；理解", 2),
    ("program", "/ˈprəʊɡræm/", "n./v. 程序；节目；计划", 1),
    ("information", "/ˌɪnfəˈmeɪʃn/", "n. 信息；资料；情报", 1),
    ("age", "/eɪdʒ/", "n./v. 年龄；时代；老化", 1),
    ("area", "/ˈeəriə/", "n. 地区；区域；面积", 1),
    ("power", "/ˈpaʊər/", "n./v. 力量；权力；电力", 2),
    ("second", "/ˈsekənd/", "n./adj. 秒；第二", 1),
    ("hour", "/aʊər/", "n. 小时；时刻；课时", 1),
    ("morning", "/ˈmɔːrnɪŋ/", "n. 早晨；上午", 1),
    ("evening", "/ˈiːvnɪŋ/", "n. 傍晚；晚上；晚会", 1),
    ("week", "/wiːk/", "n. 周；星期；一周", 1),
    ("month", "/mʌnθ/", "n. 月；月份；一个月", 1),
    ("voice", "/vɔɪs/", "n. 声音；嗓音；意见", 1),
    ("lot", "/lɒt/", "n. 许多；地块；命运", 1),
    ("difference", "/ˈdɪfrəns/", "n. 差异；不同；差额", 2),
    ("phone", "/fəʊn/", "n./v. 电话；打电话", 1),
    ("picture", "/ˈpɪktʃər/", "n. 图片；照片；电影", 1),
    ("example", "/ɪɡˈzɑːmpl/", "n. 例子；榜样；模范", 1),
    ("problem", "/ˈprɒbləm/", "n. 问题；难题", 1),
    ("law", "/lɔː/", "n. 法律；法则；规律", 2),
    ("issue", "/ˈɪʃuː/", "n. 问题；期号；发行", 2),
    ("deal", "/diːl/", "n./v. 交易；处理；发牌", 1),
    ("position", "/pəˈzɪʃn/", "n. 位置；职位；立场", 2),
    ("business", "/ˈbɪznəs/", "n. 生意；商业；事务", 1),
    ("course", "/kɔːrs/", "n. 课程；过程；路线", 1),
    ("team", "/tiːm/", "n. 队；团队；组", 1),
    ("door", "/dɔːr/", "n. 门；入口", 1),
    ("relationship", "/rɪˈleɪʃnʃɪp/", "n. 关系；联系；恋爱关系", 2),
    ("attention", "/əˈtenʃn/", "n. 注意；关注；立正", 2),
    ("service", "/ˈsɜːrvɪs/", "n. 服务；维修；兵役", 2),
    ("size", "/saɪz/", "n. 大小；尺寸；规模", 1),
    ("list", "/lɪst/", "n./v. 列表；名单；列举", 1),
    ("color", "/ˈkʌlər/", "n./v. 颜色；色彩；染色", 1),
    ("car", "/kɑːr/", "n. 汽车；车", 1),
    ("minute", "/ˈmɪnɪt/", "n. 分钟；瞬间", 1),
    ("girl", "/ɡɜːrl/", "n. 女孩；姑娘；女儿", 1),
    ("boy", "/bɔɪ/", "n. 男孩；小伙子", 1),
    # --- 常用形容词 ---
    ("good", "/ɡʊd/", "adj. 好的；有益的；善良的", 1),
    ("new", "/njuː/", "adj. 新的；刚来的；新鲜", 1),
    ("first", "/fɜːrst/", "adj./adv. 第一；首先；最先", 1),
    ("last", "/lɑːst/", "adj./adv. 最后；上一个", 1),
    ("long", "/lɒŋ/", "adj./adv. 长的；长久地", 1),
    ("great", "/ɡreɪt/", "adj. 伟大的；极好的", 1),
    ("little", "/ˈlɪtl/", "adj. 小的；幼小的", 1),
    ("own", "/əʊn/", "adj./v. 自己的；拥有", 1),
    ("right", "/raɪt/", "adj. 对的；右边的；恰当", 1),
    ("big", "/bɪɡ/", "adj. 大的；重要的", 1),
    ("high", "/haɪ/", "adj./adv. 高的；高地", 1),
    ("different", "/ˈdɪfrənt/", "adj. 不同的；各种各样", 2),
    ("small", "/smɔːl/", "adj. 小的；少的；不重要", 1),
    ("large", "/lɑːrdʒ/", "adj. 大的；宽广的", 1),
    ("next", "/nekst/", "adj./adv. 下一个；紧接着", 1),
    ("early", "/ˈɜːrli/", "adj./adv. 早的；提前的", 1),
    ("young", "/jʌŋ/", "adj. 年轻的；幼小的", 1),
    ("important", "/ɪmˈpɔːrtnt/", "adj. 重要的；有地位的", 1),
    ("possible", "/ˈpɒsəbl/", "adj. 可能的；可行的", 1),
    ("sure", "/ʃʊər/", "adj. 确信的；肯定的", 1),
    ("real", "/riːəl/", "adj. 真实的；现实的", 1),
    ("best", "/best/", "adj./adv. 最好的；最佳", 1),
    ("free", "/friː/", "adj. 自由的；免费的", 1),
    ("ready", "/ˈredi/", "adj. 准备好的；愿意的", 1),
    ("true", "/truː/", "adj. 真实的；真正的", 1),
    ("hard", "/hɑːrd/", "adj./adv. 困难的；努力地", 1),
    ("easy", "/ˈiːzi/", "adj. 容易的；轻松的", 1),
    ("bad", "/bæd/", "adj. 坏的；严重的；有害", 1),
    ("happy", "/ˈhæpi/", "adj. 快乐的；幸福的", 1),
    ("sad", "/sæd/", "adj. 悲伤的；令人难过", 1),
    ("sorry", "/ˈsɒri/", "adj. 对不起；遗憾的", 1),
    ("nice", "/naɪs/", "adj. 好的；令人愉快的", 1),
    ("old", "/əʊld/", "adj. 老的；旧的；年老", 1),
    ("beautiful", "/ˈbjuːtɪfl/", "adj. 美丽的；精彩的", 1),
    ("funny", "/ˈfʌni/", "adj. 有趣的；奇怪的", 1),
    ("crazy", "/ˈkreɪzi/", "adj. 疯狂的；热衷的", 1),
    ("smart", "/smɑːrt/", "adj. 聪明的；时髦的", 1),
    ("full", "/fʊl/", "adj. 满的；完全的", 1),
    ("open", "/ˈəʊpən/", "adj. 开放的；公开的", 1),
    ("close", "/kləʊs/", "adj./v. 近的；关闭", 1),
    ("whole", "/həʊl/", "adj. 全部的；整个的", 1),
    ("alone", "/əˈləʊn/", "adj./adv. 独自的；单独", 1),
    ("fine", "/faɪn/", "adj. 好的；细的；罚款", 1),
    ("late", "/leɪt/", "adj./adv. 晚的；迟到的", 1),
    ("wrong", "/rɒŋ/", "adj. 错误的；不对的", 1),
    ("clear", "/klɪər/", "adj. 清楚的；清澈的", 1),
    ("perfect", "/ˈpɜːrfɪkt/", "adj. 完美的；完全的", 1),
    ("terrible", "/ˈterɪbl/", "adj. 可怕的；糟糕的", 1),
    ("serious", "/ˈsɪəriəs/", "adj. 严肃的；严重的", 2),
    ("certain", "/ˈsɜːrtn/", "adj. 确定的；某个的", 2),
    ("simple", "/ˈsɪmpl/", "adj. 简单的；朴素的", 1),
    ("special", "/ˈspeʃl/", "adj. 特别的；特殊的", 1),
    ("strong", "/strɒŋ/", "adj. 强壮的；强烈的", 1),
    ("dark", "/dɑːrk/", "adj. 黑暗的；暗色的", 1),
    ("hot", "/hɒt/", "adj. 热的；辣的；性感", 1),
    ("cold", "/kəʊld/", "adj. 冷的；感冒的", 1),
    ("poor", "/pɔːr/", "adj. 贫穷的；可怜的", 1),
    ("rich", "/rɪtʃ/", "adj. 富有的；丰富的", 1),
    ("dead", "/ded/", "adj. 死的；完全的", 1),
    ("safe", "/seɪf/", "adj. 安全的；可靠的", 1),
    ("sick", "/sɪk/", "adj. 生病的；厌倦的", 1),
    ("tired", "/taɪərd/", "adj. 疲倦的；厌烦的", 1),
    ("afraid", "/əˈfreɪd/", "adj. 害怕的；担心的", 1),
    ("quiet", "/ˈkwaɪət/", "adj. 安静的；平静的", 1),
    ("normal", "/ˈnɔːrml/", "adj. 正常的；普通的", 1),
    ("upset", "/ˌʌpˈset/", "adj./v. 不安的；打翻", 1),
    ("surprised", "/səˈpraɪzd/", "adj. 惊讶的；吃惊的", 1),
    ("excited", "/ɪkˈsaɪtɪd/", "adj. 兴奋的；激动的", 1),
    ("bored", "/bɔːrd/", "adj. 无聊的；厌倦的", 1),
    ("angry", "/ˈæŋɡri/", "adj. 愤怒的；生气的", 1),
    ("lucky", "/ˈlʌki/", "adj. 幸运的；吉祥的", 1),
    # --- 常用副词/介词/连词 ---
    ("just", "/dʒʌst/", "adv. 刚刚；仅仅；恰好", 1),
    ("also", "/ˈɔːlsəʊ/", "adv. 也；同样；而且", 1),
    ("back", "/bæk/", "adv. 回；向后；以前", 1),
    ("even", "/ˈiːvn/", "adv. 甚至；连；更", 1),
    ("still", "/stɪl/", "adv. 还；仍然；更", 1),
    ("already", "/ɔːlˈredi/", "adv. 已经；早已", 1),
    ("always", "/ˈɔːlweɪz/", "adv. 总是；永远；一直", 1),
    ("never", "/ˈnevər/", "adv. 从不；决不", 1),
    ("often", "/ˈɒfn/", "adv. 经常；常常", 1),
    ("again", "/əˈɡen/", "adv. 再次；又；另外", 1),
    ("away", "/əˈweɪ/", "adv. 离开；远去；不在", 1),
    ("together", "/təˈɡeðər/", "adv. 一起；共同；同时", 1),
    ("now", "/naʊ/", "adv. 现在；立刻；当今", 1),
    ("then", "/ðen/", "adv. 那时；然后；因此", 1),
    ("here", "/hɪər/", "adv. 这里；在这里", 1),
    ("there", "/ðeər/", "adv. 那里；在那里", 1),
    ("up", "/ʌp/", "adv./prep. 向上；起来", 1),
    ("down", "/daʊn/", "adv./prep. 向下；沿着", 1),
    ("out", "/aʊt/", "adv. 出；向外；完全", 1),
    ("off", "/ɒf/", "adv./prep. 离开；关闭", 1),
    ("over", "/ˈəʊvər/", "adv./prep. 在上面；结束", 1),
    ("in", "/ɪn/", "prep./adv. 在里面；进入", 1),
    ("on", "/ɒn/", "prep./adv. 在上面；开着", 1),
    ("at", "/æt/", "prep. 在；向；以", 1),
    ("by", "/baɪ/", "prep. 被；靠近；通过", 1),
    ("for", "/fɔːr/", "prep. 为了；对于；因为", 1),
    ("with", "/wɪð/", "prep. 和；用；带有", 1),
    ("from", "/frɒm/", "prep. 从；来自；由于", 1),
    ("to", "/tuː/", "prep. 到；对；给", 1),
    ("of", "/ɒv/", "prep. 的；属于；由……组成", 1),
    ("as", "/æz/", "prep./conj. 作为；像；当", 1),
    ("but", "/bʌt/", "conj. 但是；然而；除了", 1),
    ("or", "/ɔːr/", "conj. 或者；否则；即", 1),
    ("and", "/ænd/", "conj. 和；而且；然后", 1),
    ("if", "/ɪf/", "conj. 如果；是否；假使", 1),
    ("so", "/səʊ/", "conj./adv. 所以；因此；这样", 1),
    ("because", "/bɪˈkɒz/", "conj. 因为；由于", 1),
    ("than", "/ðæn/", "conj. 比；超过", 1),
    ("while", "/waɪl/", "conj./n. 当……时；一会儿", 1),
    ("though", "/ðəʊ/", "conj. 虽然；即使；尽管", 1),
    ("after", "/ˈɑːftər/", "prep./conj. 在……之后", 1),
    ("before", "/bɪˈfɔːr/", "prep./conj. 在……之前", 1),
    ("until", "/ənˈtɪl/", "prep./conj. 直到……", 1),
    ("through", "/θruː/", "prep. 穿过；通过；因为", 1),
    ("during", "/ˈdjʊərɪŋ/", "prep. 在……期间；在……中", 1),
    ("between", "/bɪˈtwiːn/", "prep. 在……之间", 1),
    ("without", "/wɪˈðaʊt/", "prep. 没有；不；在外面", 1),
    ("under", "/ˈʌndər/", "prep. 在……下面；在……条件下", 1),
    ("against", "/əˈɡenst/", "prep. 反对；对着；靠着", 2),
    ("around", "/əˈraʊnd/", "prep./adv. 在周围；大约", 1),
    ("across", "/əˈkrɒs/", "prep./adv. 穿越；对面；横跨", 1),
    ("since", "/sɪns/", "prep./conj. 自从；既然", 1),
    ("above", "/əˈbʌv/", "prep./adv. 在……上面；以上", 1),
    ("below", "/bɪˈləʊ/", "prep./adv. 在……下面；以下", 1),
    ("suddenly", "/ˈsʌdənli/", "adv. 突然；忽然", 1),
    ("quickly", "/ˈkwɪkli/", "adv. 快速地；迅速地", 1),
    ("slowly", "/ˈsləʊli/", "adv. 慢慢地；缓慢地", 1),
    ("really", "/ˈrɪəli/", "adv. 真正地；确实；很", 1),
    ("actually", "/ˈæktʃuəli/", "adv. 实际上；竟然；真的", 1),
    ("probably", "/ˈprɒbəbli/", "adv. 大概；或许；很可能", 1),
    ("maybe", "/ˈmeɪbi/", "adv. 也许；可能；大约", 1),
    ("exactly", "/ɪɡˈzæktli/", "adv. 确切地；正是；完全", 1),
    ("almost", "/ˈɔːlməʊst/", "adv. 几乎；差不多", 1),
    ("yet", "/jet/", "adv./conj. 还；尚未；然而", 1),
    ("very", "/ˈveri/", "adv. 非常；很；真正地", 1),
    ("quite", "/kwaɪt/", "adv. 相当；完全；确实", 1),
    ("too", "/tuː/", "adv. 也；太；非常", 1),
    ("finally", "/ˈfaɪnəli/", "adv. 最后；终于；最终", 1),
    ("only", "/ˈəʊnli/", "adj./adv. 唯一的；只；仅", 1),
    ("especially", "/ɪˈspeʃəli/", "adv. 尤其；特别；专门", 2),
    ("instead", "/ɪnˈsted/", "adv. 代替；反而；作为替代", 2),
    ("mostly", "/ˈməʊstli/", "adv. 主要地；通常", 2),
    ("clearly", "/ˈklɪərli/", "adv. 清楚地；明显地", 1),
    ("apparently", "/əˈpærəntli/", "adv. 显然；似乎；据说", 2),
    ("directly", "/dɪˈrektli/", "adv. 直接地；立即；正直", 2),
    ("somewhere", "/ˈsʌmweər/", "adv. 某处；在某个地方", 1),
    ("anywhere", "/ˈeniweər/", "adv. 任何地方；在任何地方", 1),
    ("everywhere", "/ˈevrɪweər/", "adv. 到处；各处；无论哪里", 1),
    ("once", "/wʌns/", "adv./conj. 一次；曾经；一旦", 1),
    ("twice", "/twaɪs/", "adv. 两次；两倍", 1),
    ("forward", "/ˈfɔːrwərd/", "adv./adj. 向前；前进的", 1),
    ("although", "/ɔːlˈðəʊ/", "conj. 虽然；尽管；即使", 1),
    ("whether", "/ˈweðər/", "conj. 是否；不管是否", 1),
    ("unless", "/ənˈles/", "conj. 除非；如果不", 2),
    ("however", "/haʊˈevər/", "adv./conj. 然而；无论如何", 2),
    ("therefore", "/ˈðeərfɔːr/", "adv. 因此；所以", 2),
    ("otherwise", "/ˈʌðərwaɪz/", "adv./conj. 否则；不然；另外", 2),
    # --- 生活/感情/社交常用词 ---
    ("okay", "/ˌəʊˈkeɪ/", "adj./adv./int. 好的；行；可以", 1),
    ("please", "/pliːz/", "adv./v. 请；使高兴", 1),
    ("thank", "/θæŋk/", "v. 感谢；道谢", 1),
    ("welcome", "/ˈwelkəm/", "adj./v. 欢迎；受欢迎", 1),
    ("hello", "/həˈləʊ/", "int. 喂；你好", 1),
    ("goodbye", "/ˌɡʊdˈbaɪ/", "int./n. 再见；告别", 1),
    ("yes", "/jes/", "adv./n. 是；对；好的", 1),
    ("sure", "/ʃʊər/", "adj./adv. 当然；确实", 1),
    ("wow", "/waʊ/", "int. 哇；太棒了", 1),
    ("oh", "/əʊ/", "int. 哦；啊；唉", 1),
    ("well", "/wel/", "adv./adj./int. 好；健康；嗯", 1),
    ("actually", "/ˈæktʃuəli/", "adv. 实际上；事实上", 1),
    ("seriously", "/ˈsɪəriəsli/", "adv. 认真地；严重地", 1),
    ("honestly", "/ˈɒnɪstli/", "adv. 诚实地；坦白说", 1),
    ("definitely", "/ˈdefɪnətli/", "adv. 肯定地；绝对地", 1),
    ("absolutely", "/ˈæbsəluːtli/", "adv. 绝对地；完全地", 1),
    ("totally", "/ˈtəʊtəli/", "adv. 完全地；整个地", 1),
    ("anyway", "/ˈeniweɪ/", "adv. 不管怎样；反正", 1),
    ("whatever", "/wɒtˈevər/", "pron. 无论什么；随便", 1),
    ("stuff", "/stʌf/", "n. 东西；物品；材料", 1),
    ("thing", "/θɪŋ/", "n. 事情；物品；情况", 1),
    ("something", "/ˈsʌmθɪŋ/", "pron. 某事；某物；有点儿", 1),
    ("nothing", "/ˈnʌθɪŋ/", "pron. 什么都没有；零", 1),
    ("everything", "/ˈevriθɪŋ/", "pron. 一切；每件事", 1),
    ("anything", "/ˈeniθɪŋ/", "pron. 任何事；某事", 1),
    ("someone", "/ˈsʌmwʌn/", "pron. 某人；有人", 1),
    ("everyone", "/ˈevrɪwʌn/", "pron. 每个人；人人", 1),
    ("nobody", "/ˈnəʊbɒdi/", "pron. 没有人；无名之辈", 1),
    ("anyone", "/ˈeniːwʌn/", "pron. 任何人；不论谁", 1),
    # --- 情感/关系 ---
    ("date", "/deɪt/", "n./v. 日期；约会；约会", 1),
    ("kiss", "/kɪs/", "v./n. 亲吻；接吻", 1),
    ("hug", "/hʌɡ/", "v./n. 拥抱；抱紧", 1),
    ("marriage", "/ˈmærɪdʒ/", "n. 婚姻；结婚；婚礼", 1),
    ("wedding", "/ˈwedɪŋ/", "n. 婚礼；婚典；结婚纪念", 1),
    ("baby", "/ˈbeɪbi/", "n. 婴儿；宝贝；心肝", 1),
    ("kid", "/kɪd/", "n./v. 孩子；开玩笑", 1),
    ("guy", "/ɡaɪ/", "n. 家伙；男人；人们", 1),
    ("girlfriend", "/ˈɡɜːrlfrend/", "n. 女朋友；女性朋友", 1),
    ("boyfriend", "/ˈbɔɪfrend/", "n. 男朋友", 1),
    ("husband", "/ˈhʌzbənd/", "n. 丈夫；老公", 1),
    ("wife", "/waɪf/", "n. 妻子；老婆", 1),
    ("couple", "/ˈkʌpl/", "n. 一对；夫妻；几个", 1),
    ("together", "/təˈɡeðər/", "adv. 一起；共同", 1),
    ("relationship", "/rɪˈleɪʃnʃɪp/", "n. 关系；联系", 1),
    ("break up", "/breɪk ʌp/", "v. 分手；解散；打碎", 1),
    # --- 地点/空间 ---
    ("apartment", "/əˈpɑːrtmənt/", "n. 公寓；套间", 1),
    ("kitchen", "/ˈkɪtʃɪn/", "n. 厨房；厨房用具", 1),
    ("couch", "/kaʊtʃ/", "n. 沙发；长椅", 1),
    ("coffee", "/ˈkɒfi/", "n. 咖啡；咖啡色", 1),
    ("restaurant", "/ˈrestrɒnt/", "n. 餐厅；饭店", 1),
    ("store", "/stɔːr/", "n./v. 商店；储存", 1),
    ("hospital", "/ˈhɒspɪtl/", "n. 医院", 1),
    ("museum", "/mjuːˈziːəm/", "n. 博物馆；展览馆", 1),
    ("movie", "/ˈmuːvi/", "n. 电影；电影院", 1),
    ("theater", "/ˈθɪətər/", "n. 剧院；电影院；战场", 1),
    ("park", "/pɑːrk/", "n./v. 公园；停车场；停放", 1),
    ("garden", "/ˈɡɑːrdn/", "n. 花园；庭院", 1),
    ("bathroom", "/ˈbɑːθruːm/", "n. 浴室；洗手间", 1),
    ("bedroom", "/ˈbedrʊm/", "n. 卧室；寝室", 1),
    # --- 工作/职业 ---
    ("doctor", "/ˈdɒktər/", "n. 医生；博士；修理", 1),
    ("teacher", "/ˈtiːtʃər/", "n. 教师；老师", 1),
    ("actor", "/ˈæktər/", "n. 演员；行动者", 1),
    ("lawyer", "/ˈlɔːjər/", "n. 律师；法律工作者", 1),
    ("manager", "/ˈmænɪdʒər/", "n. 经理；管理者", 1),
    ("boss", "/bɒs/", "n. 老板；上司", 1),
    ("meeting", "/ˈmiːtɪŋ/", "n. 会议；见面；集会", 1),
    ("interview", "/ˈɪntəvjuː/", "n./v. 面试；采访；接见", 1),
    ("career", "/kəˈrɪər/", "n. 职业；事业；生涯", 2),
    ("salary", "/ˈsæləri/", "n. 工资；薪水", 2),
    # --- 健康/身体 ---
    ("sick", "/sɪk/", "adj. 生病的；恶心的", 1),
    ("healthy", "/ˈhelθi/", "adj. 健康的；有益健康", 1),
    ("exercise", "/ˈeksəsaɪz/", "n./v. 锻炼；练习；行使", 1),
    ("sleep", "/sliːp/", "v./n. 睡觉；睡眠", 1),
    ("tired", "/taɪərd/", "adj. 疲倦的；厌倦的", 1),
    ("pain", "/peɪn/", "n. 痛苦；疼痛；苦恼", 1),
    # --- 技术/现代 ---
    ("internet", "/ˈɪntərnet/", "n. 互联网；因特网", 1),
    ("computer", "/kəmˈpjuːtər/", "n. 计算机；电脑", 1),
    ("email", "/ˈiːmeɪl/", "n./v. 电子邮件；发邮件", 1),
    ("website", "/ˈwebsaɪt/", "n. 网站；网页", 1),
    ("social", "/ˈsəʊʃl/", "adj. 社会的；社交的", 2),
    ("message", "/ˈmesɪdʒ/", "n./v. 信息；消息；发消息", 1),
    ("technology", "/tekˈnɒlədʒi/", "n. 技术；科技；工艺", 2),
    ("screen", "/skriːn/", "n./v. 屏幕；银幕；筛选", 1),
    ("data", "/ˈdeɪtə/", "n. 数据；资料；信息", 2),
    # --- 自然/环境 ---
    ("sun", "/sʌn/", "n. 太阳；阳光；日光", 1),
    ("sky", "/skaɪ/", "n. 天空；天", 1),
    ("rain", "/reɪn/", "n./v. 雨；下雨", 1),
    ("wind", "/wɪnd/", "n. 风；气息；肠气", 1),
    ("fire", "/faɪər/", "n./v. 火；开除；点火", 1),
    ("flower", "/ˈflaʊər/", "n. 花；开花植物", 1),
    ("tree", "/triː/", "n. 树；树木；家谱", 1),
    ("animal", "/ˈænɪml/", "n. 动物；禽兽", 1),
    ("dog", "/dɒɡ/", "n. 狗；男人；跟踪", 1),
    ("cat", "/kæt/", "n. 猫；女人", 1),
    ("bird", "/bɜːrd/", "n. 鸟；人；飞机", 1),
    # --- 数字/时间 ---
    ("today", "/təˈdeɪ/", "n./adv. 今天；现在", 1),
    ("yesterday", "/ˈjestərdeɪ/", "n./adv. 昨天；以前", 1),
    ("tomorrow", "/təˈmɒrəʊ/", "n./adv. 明天；将来", 1),
    ("future", "/ˈfjuːtʃər/", "n./adj. 未来；将来；将来的", 1),
    ("past", "/pɑːst/", "n./adj. 过去；以往；过去的", 1),
    ("sometimes", "/ˈsʌmtaɪmz/", "adv. 有时；偶尔", 1),
    ("usually", "/ˈjuːʒuəli/", "adv. 通常；惯常地", 1),
    ("recently", "/ˈriːsntli/", "adv. 最近；近来", 1),
    ("ago", "/əˈɡəʊ/", "adv. 以前；...前", 1),
    ("later", "/ˈleɪtər/", "adv. 后来；稍后；以后", 1),
    ("soon", "/suːn/", "adv. 不久；很快；早", 1),
    ("tonight", "/təˈnaɪt/", "n./adv. 今晚；今夜", 1),
    # --- 口语习语 ---
    ("seriously", "/ˈsɪəriəsli/", "adv. 认真地；说正经的", 1),
    ("actually", "/ˈæktʃuəli/", "adv. 实际上；你知道吗", 1),
    ("basically", "/ˈbeɪsɪkli/", "adv. 基本上；主要地", 1),
    ("literally", "/ˈlɪtərəli/", "adv. 真的；字面地；简直", 2),
    ("apparently", "/əˈpærəntli/", "adv. 看起来；显然", 2),
    ("obviously", "/ˈɒbviəsli/", "adv. 明显地；显然地", 1),
    ("exactly", "/ɪɡˈzæktli/", "adv. 确实；正是；一点不差", 1),
    ("somehow", "/ˈsʌmhaʊ/", "adv. 不知何故；以某种方式", 2),
    ("anyway", "/ˈeniweɪ/", "adv. 总之；不管怎样", 1),
    ("else", "/els/", "adj./adv. 其他的；另外", 1),
    ("else", "/els/", "adv. 另外；否则", 1),
    ("already", "/ɔːlˈredi/", "adv. 已经；这么快", 1),
    ("still", "/stɪl/", "adv. 还；仍然；甚至更", 1),
]

def build_friends_scene(word, meaning):
    """生成简单的老友记风格对话"""
    # 用占位符，后续可批量调用LLM生成高质量场景
    scenes = {
        "default": f'Ross: Did you just say "{word}"?\nChandler: I say "{word}" all the time. It means {meaning.split("；")[0]}.\nMonica: You guys, stop debating and come eat!',
        "default_cn": f'罗斯：你刚才说的是"{word}"吗？\n钱德勒：我一直说"{word}"。意思是{meaning.split("；")[0].replace("v. ","").replace("n. ","").replace("adj. ","").replace("adv. ","")}。\n莫妮卡：你们，别争了，来吃饭吧！',
    }
    return scenes["default"], scenes["default_cn"]


def make_example_sentence(word, meaning):
    """生成简单例句"""
    examples = {
        "he": ("He is my best friend.", "他是我最好的朋友。"),
        "she": ("She loves to read books.", "她喜欢看书。"),
        "we": ("We are going to the park.", "我们要去公园了。"),
        "they": ("They arrived late last night.", "他们昨晚很晚才到。"),
        "it": ("It is raining outside.", "外面在下雨。"),
        "this": ("This is a great idea!", "这是个好主意！"),
        "that": ("That movie was amazing.", "那部电影太棒了。"),
    }
    if word in examples:
        return examples[word]
    # Generic fallback
    core = meaning.split("；")[0].replace("v. ","").replace("n. ","").replace("adj. ","").replace("adv. ","").replace("pron. ","").replace("prep. ","").replace("conj. ","").replace("int. ","").strip()
    return (f"I need to {word} this right now.", f"我现在需要{core}这件事。")


def expand_vocabulary():
    """读取现有词库，追加新词，去重，写回"""
    with open(DATA_FILE, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    existing_words = {w['word'].lower() for w in existing}
    print(f"现有词数: {len(existing)}")
    
    new_entries = []
    skipped = 0
    
    for item in WORDS_TO_ADD:
        word, phonetic, meaning, level = item
        if word.lower() in existing_words:
            skipped += 1
            continue
        
        # 生成例句
        sentence, sentence_cn = make_example_sentence(word, meaning)
        
        # 生成老友记场景
        scene, scene_cn = build_friends_scene(word, meaning)
        
        entry = {
            "word": word,
            "phonetic": phonetic,
            "meaning": meaning,
            "level": level,
            "sentence": sentence,
            "sentence_cn": sentence_cn,
            "friends_scene": scene,
            "friends_cn": scene_cn
        }
        new_entries.append(entry)
        existing_words.add(word.lower())
    
    print(f"跳过重复词: {skipped}")
    print(f"新增词数: {len(new_entries)}")
    
    combined = existing + new_entries
    # 去重（按word字段）
    seen = set()
    deduped = []
    for w in combined:
        k = w['word'].lower()
        if k not in seen:
            seen.add(k)
            deduped.append(w)
    
    # 按level然后按word排序
    deduped.sort(key=lambda x: (x.get('level',1), x['word'].lower()))
    
    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        json.dump(deduped, f, ensure_ascii=False, indent=2)
    
    print(f"✅ 词库已更新：{len(deduped)} 个词 → {DATA_FILE}")
    return len(deduped)


if __name__ == "__main__":
    total = expand_vocabulary()
    print(f"\n词库总词数：{total}")
    if total < 500:
        print("⚠️  词数不足500，需要继续补充")
    elif total >= 1000:
        print("🎉 词库已达1000词！")
    else:
        print(f"📈 已有 {total} 词，还需 {1000-total} 词达到1000")
